version: '3'

services:
  web:
    build: .
    restart: always
    ports:
    - 8000:80
    tty: true
    volumes:
    - ./logs:/var/log/nginx
#    - ./src:/home/components/helloworld
    depends_on:
    - db
    environment:
      SITE_NAME: ${SITE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}

  db:
    image: mysql:5.7
    command: mysqld
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    tty: true
